# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  LIBOBS: C:/Deps/obs/build/libobs
  LSL: C:/Deps/liblsl/share/LSL
  OBSDEPS: C:/Deps/obs-deps/win64

stages:
  - build
  - release

before_script:
#  - echo "Before script section"
#  - echo "For example you might run an update here or install a build dependency"
#  - echo "Or perhaps you might print out some debugging details"

after_script:
#  - echo "After script section"
#  - echo "For example you might do some cleanup here"

build-plugin:
  stage: build
  tags:
    - win
  script:
    # prepare build environement
    - mkdir build
    - cd build
    # Configure cmake
    - cmake -DLibObs_DIR="$LIBOBS" -DLSL_DIR="$LSL" -DOBSDEPS_DIR="$OBSDEPS" ..
    # Build plugin (release + Debug)
    - cmake --build . --target ALL_BUILD --config Debug
    - cmake --build . --target ALL_BUILD --config Release
  artifacts:
    paths:
      - build/src/Debug/lsl_plugin.dll
      - build/src/Debug/lsl_plugin.lib
      - build/src/Debug/lsl_plugin.pdb
      - build/src/Debug/lsl_plugin.exp
      - build/src/Release/*
    expire_in: 2 days


release:
  stage: release
  tags:
    - docker
  image: python:3.8-slim
  script:
    - pip3 install gitlab-release
    # Add data to the release
    - cp -r data build/src/Release/bin
    # Make the release
    - cd build/src/Release
    - gitlab-release --zip "release-${CI_COMMIT_TAG}.zip" --description "Install the dll in the OBS plugin directory, and the content of the bin directory in the OBS bin directory" *
  # Only release if the reference is not a branch and corresponds to a v'digit'.'something'
  only:
    - /v\d+\..+/
  except:
    - branches
